travis:
  secure:
    BINSTAR_TOKEN: aetKk7V6Y3yNk3PCs4u2qEQBDsAQqWuP4L6IL8GP4AgCoLsE/77KuKe2NQZ0hJAAPldJmGvOcgqjmPF5Yy8Ma7YfLPW2hfcQv+UDAYKcNw5fE03jQtksF4jN0x49mmIyL0/X0QpIldqkVnCvLAH8YlJzb/jDFZ2P5YrjC1pO2HobKBERx79jmt6TBnO4yoKMulhoXSJSs6AvbxA9H5M3YTynjZbF5w8X7mo91GZkQGlWzrO3WBXnUHfmjCwqUPjQLzNlpd8m7tGKJ8i+Gh/8/tuCGRcCmlEvw2q+2iqlWIjIu4quhz2Q8w+PLECAdMW735F/vlRvppL2MojHQxh3yc+xM8xcidK9hmdUIcmnZu9WYciyY+5zEX5pR/Qx0tUg/lTUKj5d7nzvN94ToSxuGnbBLhnazL7TgHsYVdOere4v5cuem81+k79utd6lrXvq2dIFAxq/xlxfg6f70sK4VxzljAnMUo7eqEE2h3gH4pp++gPYUwb8sOOu0ENokc5qbogNteEvIc/IqmcsoqzJ8X2rNav3MIe/MaMH7ounwF5s/KXus7donz/Y2r0HMXdLBYissJTftQ4wfgELt2zul3nnos+m6iCAnG+yR6va9bCZVFPUosWRS25/ZA7rLuMOOV327YRaQ1aR8H79O4/IIbcYUBUcj2iHp1UM95ZXJCE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
